# Generated by Django 3.0.5 on 2020-04-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_board_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
