# Generated by Django 3.0.5 on 2020-04-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_board_app', '0003_auto_20200419_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
