# Generated by Django 3.0.5 on 2020-04-19 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_user_app', '0001_initial'),
        ('movie_board_app', '0004_auto_20200419_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='recommender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_user_app.Recommender'),
        ),
        migrations.DeleteModel(
            name='Recommender',
        ),
    ]
