# Generated by Django 3.0.5 on 2020-04-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_board_app', '0005_auto_20200419_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_score',
            field=models.FloatField(default=0),
        ),
    ]
