# Generated by Django 3.0.5 on 2020-04-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_board_app', '0006_movie_imdb_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='recommendee',
            new_name='recommendee_first_name',
        ),
        migrations.AddField(
            model_name='movie',
            name='recommendee_last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
