# Generated by Django 3.0.5 on 2020-04-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_board_app', '0007_auto_20200419_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='recommendee_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='recommendee_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='youtube_trailer_link',
            field=models.CharField(default='', max_length=250),
        ),
    ]
